#应用名称
spring:
  application:
    name: snowwhite
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#应用端口号
server:
  port: 8089
  servlet:
    context-path: /snowwhite