#应用名称
spring:
  application:
    name: kvps
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:h2:mem:kvps;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    passoword: 
  h2:
    console:
      enabled: true
      path: /h2
      settings: 
        web-allow-others: true

#应用端口号
server:
  port: 8089
  servlet:
    context-path: /${spring.application.name}

excel:
  data:
    devops:
      file: E:/slicee/ws/gitws/kvps/src/test/java/gbench/sandbox/weihai/data/devops_data.xlsx